CREATE TABLE IF NOT EXISTS PRODUCT (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  description VARCHAR(1000),
  price DOUBLE,
  quantity INT
);

INSERT INTO PRODUCT (NAME, DESCRIPTION, PRICE, QUANTITY) VALUES ('Pen','Blue pen',10,100);
